### ISSUE TITLE
Training with custom dataset

### ISSUE THREAD

**Issue by StepTurtle** [IrohXu/lanenet-lane-detection-pytorch#7]
Hello, I have got issue when i am trying to train my custom dataset:

```
Use ENet as backbone
25 epochs 1240 training samples

Epoch 0/24
----------
Traceback (most recent call last):
  File "train.py", line 87, in <module>
    train()
  File "train.py", line 72, in train
    model, log = train_model(model, optimizer, scheduler=None, dataloaders=dataloaders, dataset_sizes=dataset_sizes, device=DEVICE, loss_type=args.loss_type, num_epochs=args.epochs)
  File "/home/bzeren/lanenet-lane-detection-pytorch/model/lanenet/train_lanenet.py", line 75, in train_model
    loss = compute_loss(outputs, binarys, instances, loss_type)
  File "/home/bzeren/lanenet-lane-detection-pytorch/model/lanenet/train_lanenet.py", line 28, in compute_loss
    var_loss, dist_loss, reg_loss = ds_loss_fn(pix_embedding, instance_label)
  File "/home/bzeren/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bzeren/lanenet-lane-detection-pytorch/model/lanenet/loss.py", line 59, in forward
    return self._discriminative_loss(input, target)
  File "/home/bzeren/lanenet-lane-detection-pytorch/model/lanenet/loss.py", line 64, in _discriminative_loss
    seg_gt = seg_gt.reshape(batch_size, H*W)
RuntimeError: shape '[1, 131072]' is invalid for input of size 393216
```
Do any of you have any ideas on solving the problem? Thanks in advance for your help.

**Comment by StepTurtle** [comment]
This is my arguments:

```
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", help="Dataset path")
    parser.add_argument("--model_type", help="Model type", default='ENet')
    parser.add_argument("--loss_type", help="Loss type", default='FocalLoss')
    parser.add_argument("--save", required=False, help="Directory to save model", default="./log")
    parser.add_argument("--epochs", required=False, type=int, help="Training epochs", default=25)
    parser.add_argument("--width", required=False, type=int, help="Resize width", default=512)
    parser.add_argument("--height", required=False, type=int, help="Resize height", default=256)
    parser.add_argument("--bs", required=False, type=int, help="Batch size", default=1)
    parser.add_argument("--val", required=False, type=bool, help="Use validation", default=False)
    parser.add_argument("--lr", required=False, type=float, help="Learning rate", default=0.0001)
    parser.add_argument("--pretrained", required=False, default=None, help="pretrained model path")
    parser.add_argument("--image", default="./output", help="output image folder")
    parser.add_argument("--net", help="backbone network")
    parser.add_argument("--json", help="post processing json")
    return parser.parse_args()
```

**Comment by batuhanbeytekin** [comment]
You should try to change your binary and instance input images shape from 3 channels to 1 channel.

**Comment by StepTurtle** [comment]
Thanks for your advice, it works.

**Comment by StepTurtle** [comment]
Thanks for your advice, it works.
